language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
- nightly
script:
- python -m unittest
deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  on:
    tags: true
